from praks2.ylesanne10.kasutajad3 import Kasutajad
kasutaja1 = Kasutajad("Janre", "Liiv")
kasutaja1.maara_kasutajanimi("Janre.Liiv")
kasutaja1.maara_parool("1111")
kasutaja1.kirjelda_kasutaja()
kasutaja1.tervita_kasutaja()
kasutaja1.suurenda_sisselogimiskatsed()
kasutaja1.suurenda_sisselogimiskatsed()
kasutaja1.suurenda_sisselogimiskatsed()
kasutaja1.suurenda_sisselogimiskatsed()
kasutaja1.suurenda_sisselogimiskatsed()
print("Kasutaja on sisse loginud " + str(kasutaja1.sisselogimiskatsed) + " korda.")
kasutaja1.reset_sisselogimiskatsed()
print(kasutaja1.sisselogimiskatsed)

kasutaja2 = Kasutajad("Ax-Sylvester", "Hommuk")
kasutaja2.maara_kasutajanimi("Ax-Sylvaster.Hommuk")
kasutaja2.maara_parool("2222")
kasutaja2.kirjelda_kasutaja()
kasutaja2.tervita_kasutaja()
kasutaja2.suurenda_sisselogimiskatsed()
kasutaja2.suurenda_sisselogimiskatsed()
kasutaja2.suurenda_sisselogimiskatsed()
kasutaja2.suurenda_sisselogimiskatsed()
print("Kasutaja on sisse loginud " + str(kasutaja2.sisselogimiskatsed) + " korda.")
kasutaja2.reset_sisselogimiskatsed()
print(kasutaja2.sisselogimiskatsed)

kasutaja3 = Kasutajad("Olaf Olev", "Alakivi")
kasutaja3.maara_kasutajanimi("Olaf-Olev.Alakivi")
kasutaja3.maara_parool("3333")
kasutaja3.kirjelda_kasutaja()
kasutaja3.tervita_kasutaja()
kasutaja3.suurenda_sisselogimiskatsed()
kasutaja3.suurenda_sisselogimiskatsed()
kasutaja3.suurenda_sisselogimiskatsed()
print("Kasutaja on sisse loginud " + str(kasutaja3.sisselogimiskatsed) + " korda.")
kasutaja3.reset_sisselogimiskatsed()
print(kasutaja3.sisselogimiskatsed)